azure:
  free_disk_space: true
  store_build_artifacts: true
conda_build:
  error_overlinking: true
conda_forge_output_validation: true
build_platform:
   linux_aarch64: linux_64
github:
  branch_name: main
  tooling_branch_name: main
provider:
  linux_aarch64: default
